### ISSUE TITLE
Create NavProgress-component (prev/save/next section)

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/cash-program-design-wizard#112]
- [x] Create new component
- [x] Navigate back + forward
- [x] Disable Prev/Back-button on first section
- [x] Disable Next-button on last section
- [x] Handle "Save"-section action
- [x] Tweak lay-out/styling

**Comment by arsforza** [comment]
@elwinschmitz how do I fix this?
![2021-10-01_16h29_00](https://user-images.githubusercontent.com/63000678/135637287-243439ef-a160-47cd-8ed7-37834d9ea498.png)

**Comment by elwinschmitz** [comment]
Hmm. Weird. 
Does it make a difference from which folder you run the command? (It shouldn't, but maybe..)

Otherwise you could look into the tool Husky itself. Maybe it isn't properly installed or something?

It's also possible to do `git push` without running these automated commands. With the `--no-verify` flag. If all else fails...
