### ISSUE TITLE
Add a link to the Report/input-page on template-variables/placeholders

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/cash-program-design-wizard#296]
To easily add a missing answer. 

## To Do
- [x] don't delete the (sub-)section IDs from QuestionInput objects
- [x] Pass through to `answers`-array in Report-page (if not automatic already)
- [x] Add `routerLink` to answer-placeholders
- [x] Update `title`-attributes with "Jump/Go to"-text

**Comment by arsforza** [comment]
task 2 - new array of `{ questionName, sectionName }`
task 3 - used `href` because `routerLink` doesn't work with Markup

**Comment by elwinschmitz** [comment]
As an addition to the old-school `a[href]` approach, there is a way to fake the `routerLink` behavior. 
See: https://www.semicolonworld.com/question/68948/can-39-t-render-routerlink-in-innerhtml-in-angular#comment-21

So a listener for clicks inside the report, check for 'internal'/relative links and do the router thing, otherwise do the native browser thing.
