### ISSUE TITLE
Create Program-page (with routing-parameters etc)

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/cash-program-design-wizard#30]
The 'detail-view' of a "program". So that each program can have its own URL.
For example:
 https://cpdw.example.org/program/1
 or https://cpdw.example.org/program/asdf1Q2w34ty...9yz (so using a long unique hash/id)

### Filtering
Filters can be set via query-parameters, like:
`/program/1/?role=hq` and `/program/1/?role=if&topic=people`

So this would automatically set/load these filters when loading the page.

## To Do
- [x] Create page + module
- [x] Configure routing-parameters
- [x] Show routing values in the page/debug-container
- [x] Tests?

**Comment by arsforza** [comment]
@elwinschmitz 
I tested page creation, don't know if this is what you had in mind for this item

https://github.com/rodekruis/cash-program-design-wizard/tree/test-30--create-program-page
