### ISSUE TITLE
Offline work/sync features

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/cash-program-design-wizard#357]
See #34 

## To Create backlog-items:
- "You're offline"-notification floating in top-right (on unexpected events);  
  See #396 
- Question/Answer state indication  
  See #397
- "save-progress/status"-indicator (persistent)  
  See #398

**Comment by talrosenthal** [comment]
Question: How does the form work in an offline state? will it still autosave? Will they need to save if it's offline but autosave when online?
