### ISSUE TITLE
Create "test data only"-program (and include in reset-endpoint)

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/cash-program-design-wizard#390]

**Comment by RubenGeo** [comment]
-  You can now seed test data only using  `"script": "test"` in the rest end point
- The `demo` seed still seeds the test questions and sections. I'm not sure if we want to remove that @arsforza @elwinschmitz

**Comment by elwinschmitz** [comment]
I think the test-data can be removed from the `demo`-seed-script, but I think with the current set-up you can't have both programs exist side-by-side at the same time, right @RubenGeo?

I guess the quickest way around that would be to remove the `truncateAll`-call from both scripts and maybe add a third `reset`-script that only does that, or something?

**Comment by RubenGeo** [comment]
- Yes that's true that cannot live side by side for now
- Would multiple programs work in the interface now?
  - There is no ' select assigned programs' interface right?
  - /programs now return only the assigned programs for a user
  - So then I assume you can switch programs if we create extra users and assign them all just one program
- I would maybe let the demo option in the reset script just always seed both programs with different user so you can siwtch programs by logging in and out?

**Comment by elwinschmitz** [comment]
>     * Would multiple programs work in the interface now?
Yes and "not fully". ;)

>       * There is no ' select assigned programs' interface right?
No. But different URLs can be used for each individual program.

>       * /programs now return only the assigned programs for a user

The interface will use the first program only, automatically.
But the URL can be switched manually after that anyway.

>       * So then I assume you can switch programs if we create extra users and assign them all just one program

That could be a workaround, to create a `edit-program1`-user and a `edit-program2`-user.

>     * I would maybe let the demo option in the reset script just always seed both programs with different user so you can siwtch programs by logging in and out?

If that is not too much work, that would be a feasible workaround indeed.
But we shouldn't have too many different ENV-variables for all these special users or anything...

Investing some time in a "list all my assigned programs"-feature in the interface would be a better way to spend our time, I guess.

**Comment by elwinschmitz** [comment]
For now we've decided this is a "during development only"-feature,
So we will revisit when we're going to work with "multiple-programs at the same time".

See #424
And #428
