### ISSUE TITLE
Only enable comments per sub-section (not for every question)

### ISSUE THREAD

**Issue by ORCANLRC** [rodekruis/cash-program-design-wizard#427]
As an end user I only need one comment section per card, so its easier to comment and cimmunicate about multiple questiosn in one card. @elwinschmitz

**Comment by elwinschmitz** [comment]
Ah, so technically we could make it that the comments-sections is only visible for "the final question of a sub-section".
Maybe regardless of the question-type now then?

So it would be possible again to have a "multiple choice"-question at the end of a sub-section, that would have the comments-section attached..
