### ISSUE TITLE
Automagically update DB-contents incrementally

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/cash-program-design-wizard#526]
## Requirements
- Create a backup/dump of existing data beforehand (for rollback)
- Endpoint to create an export of current data into a CSV
- Endpoint to import/overwrite the DB with new data from a CSV

### Scope/limitations (for now)
- Only ADDING/UPDATING questions, no automatic deleting

### CSV 'structure'
- The CSV will be 'flat' with rows-per-question.
- All 'parent' items will be separate columns, so `section`, `section_prio`, `subsection`, `subsection_prio`
- All 'child' items will be separate columns at the end, so `option1_name`, `option1_label`, `option2_name`, `option2_label`, ..., `option15_name`, `option15_label`. (hard-coded to max 15)

### Workflow
- First use the export-endpoint to create the backup/starting-point CSV
- Make changes in Excel
- Upload the new CSV to the import-endpoint

## To Do
- [x] Create export endpoint + logic, See #527
- [x] Create import endpoint
  - [x] create "adding only" logic
  - [x] create "update when available" logic
  - [x] handle errors?
- [x] ?

**Comment by elwinschmitz** [comment]
@RubenGeo 
Some test-files: (by using the defaults "Save as..."-features from Excel (on macOS)

- [cpdw-export-all_2022-02-14.csv](https://github.com/rodekruis/cash-program-design-wizard/files/8078186/cpdw-export-all_2022-02-14.csv)
- [cpdw-export-all_2022-02-14.xlsx](https://github.com/rodekruis/cash-program-design-wizard/files/8078187/cpdw-export-all_2022-02-14.xlsx)
- [cpdw-export-all_2022-02-14.excel-export.csv](https://github.com/rodekruis/cash-program-design-wizard/files/8078188/cpdw-export-all_2022-02-14.excel-export.csv)
- [cpdw-export-all_2022-02-14.excel-export-ms-dos.csv](https://github.com/rodekruis/cash-program-design-wizard/files/8078189/cpdw-export-all_2022-02-14.excel-export-ms-dos.csv)
- [cpdw-export-all_2022-02-14.excel-export-utf-8.csv](https://github.com/rodekruis/cash-program-design-wizard/files/8078190/cpdw-export-all_2022-02-14.excel-export-utf-8.csv)

I made some deliberate errors in some of these files while testing, but I'm not sure these 'typos' are still in the files above...

**Comment by RubenGeo** [comment]
Update about the work I did yeserday:

- Adding new (sub) sections is done
- Adding new tags via csv import is done
- Putting questions in different subsections is done


Not done :

- Deleting sections
- This will not really matter because if there are sections without questions they will not show up in the interface
- Putting subsection in different sections
- This may be a bit more important to add later
