### ISSUE TITLE
ADD NEW TAG OPTIONS

### ISSUE THREAD

**Issue by ORCANLRC** [rodekruis/cash-program-design-wizard#572]
ALL >> NO CHANGE
CASH >> CHANGE TO FSP
DATA >> CEA 
PEOPLE >> NO CHANGE
NEW >> REGISTRATION
NEW >> TBD

**Comment by elwinschmitz** [comment]
I've chosen to include "coordination" as well.

Because that way it'll be a sort of "worst case"-scenario for the length of 5 tags in the layout.
