### ISSUE TITLE
SET UP DATA STORAGE

### ISSUE THREAD

**Issue by ORCANLRC** [rodekruis/cash-program-design-wizard#6]
We need to decide and define in code how all dynamic data will be stored.

This could be a database-server or a file-based approach.

- [ ] define scope/limitations/requirements
- [ ] create ideas/possible solutions
- [x] decide
- [ ] put in documentation/code (see related/linked PRs)

(@elwinschmitz wrote/edited this message, not Orla)

**Comment by elwinschmitz** [comment]
## Possible solution / initial idea
Use SQLite-based data-storage.
This limits the hassle for local development:
- the local setup of the back-end can 'just work out of the box'
- we can share "filled database-files with test/mock data
- I think our familiar tools (TypeORM?) can support this?

End-users/organizations can easily set this up on their environments/tech-stacks
- it has low/safe requirements (I think)
